script: |
            cd www/
            # Si no hay un repositorio git, clona. Si lo hay, actualiza.
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git pull origin main
            fi
            
            # Instalaci√≥n de dependencias
            composer install --no-dev --optimize-autoloader
            
            # Solo ejecutamos artisan si existe el archivo .env
            if [ -f ".env" ]; then
              php artisan migrate --force
              php artisan config:cache
              php artisan route:cache
            else
              echo "Aviso: El archivo .env no existe en el servidor. Saltando comandos de Artisan."
            fi
